# Generated by Django 4.1 on 2024-06-13 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tournois_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='tournois_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.tournois'),
        ),
    ]
