# Generated by Django 4.1 on 2024-06-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_positions_tournois_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('black_chip_positions', models.TextField()),
                ('white_chip_positions', models.TextField()),
                ('solution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemToValidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('black_chip_positions', models.TextField()),
                ('white_chip_positions', models.TextField()),
                ('solution', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='problems',
        ),
        migrations.DeleteModel(
            name='problemsToValidate',
        ),
    ]
