# Generated by Django 4.1 on 2024-06-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_problem_problemtovalidate_delete_problems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='black_chip_positions',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='white_chip_positions',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='problemtovalidate',
            name='black_chip_positions',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='problemtovalidate',
            name='white_chip_positions',
            field=models.JSONField(),
        ),
    ]
