# Generated by Django 4.1 on 2024-06-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tsumego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='sgf_metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournois'),
        ),
    ]
