# Generated by Django 4.1 on 2024-06-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournois',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
